# FastAPI Example from Docker docs 
# https://fastapi.tiangolo.com/deployment/docker/#dockerfile
FROM python:3.10-slim

# Set working directory
WORKDIR /code

# Copy requirements file and install dependencies
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# Copy application code
COPY . /code

# Command to run the application using Uvicorn
CMD ["uvicorn", "fast_test_streaming:app", "--host", "0.0.0.0", "--port", "8000"]


# docker build -t fast_test_streaming:latest .        # Build container
# docker run -p 8000:8000 fast_test_streaming:latest        # Run container
# curl http://localhost:8000/stream      # CURL container in another terminal
# docker tag fast_test_streaming:latest ghcr.io/djsaunders1997/fast_test_streaming:latest       # Tag this container in github registry format 
# docker push ghcr.io/djsaunders1997/fast_test_streaming:latest       # Push to github container registry
