# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Configuration for JavaScript dependencies in the frontend
  - package-ecosystem: "npm"
    directory: "/frontend" # Path to the directory containing package.json
    schedule:
      interval: "weekly"
    # Additional configurations like 'open-pull-requests-limit', 'ignore', etc.

  # Configuration for Python dependencies in the backend
  - package-ecosystem: "pip"
    directory: "/backend_azure_function" # Path to the directory containing requirements.txt
    schedule:
      interval: "weekly"

