# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Deploy Backend Azure Function App

on:
  push:
    branches:
      - main # Trigger for any commit in 'main'
    tags:
      - 'slot*' # Trigger for tags starting with 'slot'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "backend_azure_function" # Path to Azure Function project
  PYTHON_VERSION: "3.10"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List directory structure
        run: ls -al # Debugging helper to list files

      - name: Setup Python version
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          pip install -r requirements.txt

      # Optional: Add step to run tests here

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app

      # Set slot_name to be 'slot' if triggered via a slot tag, or 'Production' if triggered from the main branch
      - name: Determine Slot Name
        id: set_slot
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == refs/tags/slot* ]]; then
            SLOT_NAME="slot"
          else
            SLOT_NAME="Production"
          fi
          echo "::set-output name=slot_name::$SLOT_NAME"

      - name: "List directory contents"
        run: ls -al

      - name: "Deploy to Azure Functions"
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: "GPTeasers-GenerateQuiz"
          slot-name: ${{ steps.set_slot.outputs.slot_name }}
          package: "." # ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} # Already in correct directory
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8D1E903F026A45F6AFD68F162BCABB42 }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
